### ISSUE TITLE
Issue w/ npm start

### ISSUE THREAD

**Issue by micahasmith** [react-webpack-generators/generator-react-webpack#296]
Here's what happens when i run `npm start`:

```
> react-webpack1@0.0.1 test /Users/micahsmith/dev/react-webpack1
> karma start

02 11 2016 16:01:23.188:ERROR [preprocess]: Can not load "webpack"!
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'debug'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   The 'debug' property was removed in webpack 2.
   Loaders should be updated to allow passing this option via loader options in module.rules.
   Until loaders are updated one can use the LoaderOptionsPlugin to switch loaders into debug mode:
   plugins: {
     new webpack.LoaderOptionsPlugin({
       debug: true
     })
   }
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/Users/micahsmith/dev/react-webpack1/node_modules/webpack/lib/webpack.js:16:9)
    at new Plugin (/Users/micahsmith/dev/react-webpack1/node_modules/karma-webpack/lib/karma-webpack.js:63:18)
    at invoke (/Users/micahsmith/dev/react-webpack1/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/Users/micahsmith/dev/react-webpack1/node_modules/di/lib/injector.js:59:20)
    at get (/Users/micahsmith/dev/react-webpack1/node_modules/di/lib/injector.js:48:43)
    at /Users/micahsmith/dev/react-webpack1/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/Users/micahsmith/dev/react-webpack1/node_modules/di/lib/injector.js:70:31)
    at get (/Users/micahsmith/dev/react-webpack1/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/Users/micahsmith/dev/react-webpack1/node_modules/karma/lib/preprocessor.js:55:20)
    at Array.forEach (native)
    at createPreprocessor (/Users/micahsmith/dev/react-webpack1/node_modules/karma/lib/preprocessor.js:74:20)
    at Array.invoke (/Users/micahsmith/dev/react-webpack1/node_modules/di/lib/injector.js:75:15)
    at get (/Users/micahsmith/dev/react-webpack1/node_modules/di/lib/injector.js:48:43)
    at /Users/micahsmith/dev/react-webpack1/node_modules/di/lib/injector.js:71:14
    at Array.map (native)

START:
02 11 2016 16:01:23.323:INFO [karma]: Karma v1.3.0 server started at http://localhost:8080/
02 11 2016 16:01:23.324:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
02 11 2016 16:01:23.325:ERROR [karma]: Found 1 load error

> react-webpack1@0.0.1 posttest /Users/micahsmith/dev/react-webpack1
> npm run lint


> react-webpack1@0.0.1 lint /Users/micahsmith/dev/react-webpack1
> eslint ./src
```

my package.json is:

```js
{
  "name": "react-webpack1",
  "private": true,
  "version": "0.0.1",
  "description": "react-webpack1 - Generated by generator-react-webpack",
  "main": "src/index.js",
  "scripts": {
    "clean": "rimraf dist/*",
    "copy": "copyfiles -f ./src/index.html ./src/favicon.ico ./dist",
    "dist": "npm run clean && npm run copy && webpack --progress --bail --env dist -p",
    "lint": "eslint ./src",
    "posttest": "npm run lint",
    "release:major": "npm version prerelease && git push --follow-tags && npm publish --tag beta",
    "release:minor": "npm version prerelease && git push --follow-tags && npm publish --tag beta",
    "release:patch": "npm version prerelease && git push --follow-tags && npm publish --tag beta",
    "serve:dev": "webpack-dev-server --open --env dev",
    "serve:dist": "webpack-dev-server --open --env dist -p --progress",
    "start": "npm run serve:dev",
    "test": "karma start",
    "test:watch": "karma start --autoWatch=true --singleRun=false --reporters=mocha,coverage"
  },
  "repository": "",
  "keywords": [],
  "author": "Your name here",
  "devDependencies": {
    "babel-core": "^6.7.6",
    "babel-eslint": "^6.0.4",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-polyfill": "^6.9.0",
    "babel-preset-airbnb": "^2.0.0",
    "babel-preset-es2015-native-modules": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "chai": "^3.5.0",
    "copyfiles": "^1.0.0",
    "css-loader": "^0.23.1",
    "enzyme": "^2.2.0",
    "eslint": "^2.8.0",
    "eslint-config-airbnb": "^9.0.0",
    "eslint-loader": "^1.3.0",
    "eslint-plugin-import": "^1.4.0",
    "eslint-plugin-jsx-a11y": "^1.0.0",
    "eslint-plugin-react": "^5.0.0",
    "file-loader": "^0.9.0",
    "isparta-loader": "^2.0.0",
    "karma": "^1.0.0",
    "karma-chai": "^0.1.0",
    "karma-coverage": "^1.0.0",
    "karma-junit-reporter": "^1.0.0",
    "karma-mocha": "^1.0.1",
    "karma-mocha-reporter": "^2.0.3",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-sinon": "^1.0.5",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.7.0",
    "mocha": "^2.4.5",
    "null-loader": "^0.1.1",
    "phantomjs-prebuilt": "^2.1.7",
    "react-addons-test-utils": "^15.0.1",
    "react-hot-loader": "^1.3.0",
    "rimraf": "^2.5.2",
    "sinon": "^1.17.3",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^2.1.0-beta.6",
    "webpack-dev-server": "^2.0.0-beta",
    "sass-loader": "^3.2.0",
    "node-sass": "^3.7.0",
    "postcss": "^5.0.21",
    "postcss-loader": "^0.9.1"
  },
  "dependencies": {
    "react": "^15.0.1",
    "react-dom": "^15.0.1",
    "react-redux": "^4.4.5",
    "redux": "^3.6.0"
  }
}


```

**Comment by micahasmith** [comment]
```
npm uninstall webpack --save-dev 
npm install webpack@2.1.0-beta.21 --save-dev
```
