### ISSUE TITLE
V4 -- Tests break against Head of v2 template

### ISSUE THREAD

**Issue by stylesuxx** [react-webpack-generators/generator-react-webpack#305]
When using the Head of the v2 template instead of the latest tag some of the tests are breaking:

```
  1) react-webpack:app "before all" hook:
     TypeError: Cannot read property 'scripts' of undefined
      at AppGenerator.configuring (generators/app/index.js:9:3171)
      at Object.<anonymous> (node_modules/yeoman-generator/lib/base.js:439:23)
      at node_modules/run-async/index.js:26:25
      at node_modules/run-async/index.js:25:19
      at node_modules/yeoman-generator/lib/base.js:440:9

  2) react-webpack:app without cssmodules support "before all" hook:
     TypeError: Cannot read property 'scripts' of undefined
      at AppGenerator.configuring (generators/app/index.js:9:3171)
      at Object.<anonymous> (node_modules/yeoman-generator/lib/base.js:439:23)
      at node_modules/run-async/index.js:26:25
      at node_modules/run-async/index.js:25:19
      at node_modules/yeoman-generator/lib/base.js:440:9

  3) react-webpack:app with PostCSS support "before all" hook:
     TypeError: Cannot read property 'scripts' of undefined
      at AppGenerator.configuring (generators/app/index.js:9:3171)
      at Object.<anonymous> (node_modules/yeoman-generator/lib/base.js:439:23)
      at node_modules/run-async/index.js:26:25
      at node_modules/run-async/index.js:25:19
      at node_modules/yeoman-generator/lib/base.js:440:9

```

Looking into it.

**Comment by stylesuxx** [comment]
Nevermind, I was on the wrong branch - sorry for the confusion
